### ISSUE TITLE
Error: cannot find module 'node:http'

### ISSUE THREAD

**Issue by sunkast** [Gyran/MMM-plex-recently-added#11]
I updated to the latest version tonight and now it's broken again.

```
[26.04.2023 01:45.12.463] [ERROR] Error: Cannot find module 'node:http'
Require stack:
- /opt/magic_mirror/modules/MMM-plex-recently-added/node_helper.js
- /opt/magic_mirror/js/app.js
- /opt/magic_mirror/serveronly/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-plex-recently-added/node_helper.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/magic_mirror/modules/MMM-plex-recently-added/node_helper.js',
    '/opt/magic_mirror/js/app.js',
    '/opt/magic_mirror/serveronly/index.js'
  ]
}
```

Running this docker image: `bastilimbach/docker-magicmirror:latest`

**Comment by Gyran** [comment]
Fixed again!

**Comment by Gyran** [comment]
[bastilimbach/docker-magicmirror:latest](https://hub.docker.com/r/bastilimbach/docker-magicmirror) uses an really old version of node (12 which reached end of life April 2022) and seems to be [unmaintained](https://github.com/bastilimbach/docker-MagicMirror/issues/48).
But i've done some changes to make sure that this module will stay compatible with node 12 since it still got a lot of downloads.
Seems like magic mirror recommends [karsten13/magicmirror](https://hub.docker.com/r/karsten13/magicmirror/)  now instead.
https://docs.magicmirror.builders/getting-started/installation.html#docker-image

**Comment by zzarbi** [comment]
FYI @Gyran this https://khassel.gitlab.io/magicmirror/installation/ this like a newer version for MagicMirror docker, it support node 18 and 19.

_Edited_
Jut realized you said the same thing ahah
